### ISSUE TITLE
scrollTo in ViewActions cannot be applied to (org.hamcrest.Matcher<android.view.View>

### ISSUE THREAD

**Issue by vmarasow** [googlecodelabs/android-testing#1]
Line: 124 - Getting an error that scrollTo doesn't work with a Matcher as a parameter

https://github.com/googlecodelabs/android-testing/blob/master/app/src/androidTest/java/com/example/android/testing/notes/notes/NotesScreenTest.java

**Comment by slinzner** [comment]
Hey thanks for reporting this. Would be great to get a bit more info. Can please paste the logcat output here? Also would be great to know which device/emulator you're running on.

**Comment by vmarasow** [comment]
My bad, auto imports imported from the wrong package

**Comment by AeroEchelon** [comment]
Had run into the same issue as well. There were unreferenced imports that were automagically being cleaned up by Android Studio.

For future developers go to:

![image](https://cloud.githubusercontent.com/assets/2360095/12869130/15059562-cce4-11e5-95d3-9d7ba1855942.png)

And uncheck _Optimize imports on the fly_.
