### ISSUE TITLE
Comment on the note that unit tests should make up 70% of your tests

### ISSUE THREAD

**Issue by cketti** [googlecodelabs/android-testing#10]
> Did you know that unit tests should make up to 70% of your tests?

I believe that a statement like this is useless without further explanation or a link to more information. You could point readers to the article [Just Say No to More End-to-End Tests](http://googletesting.blogspot.com/2015/04/just-say-no-to-more-end-to-end-tests.html).

**Comment by slinzner** [comment]
Fixed, great suggestion!
