### ISSUE TITLE
404 page error

### ISSUE THREAD

**Issue by GlenMonad** [googlecodelabs/android-testing#111]
https://codelabs.developers.google.com/codelabs/android-testing/index.html?index=..%2F..index#11

Espresso Cheat Sheet(https://google.github.io/android-testing-support-library/docs/espresso/cheatsheet/) this link is broken

**Comment by dmeng** [comment]
Should be fixed now; "Espresso Cheat Sheet" should link to https://developer.android.com/training/testing/espresso/cheat-sheet
