### ISSUE TITLE
Android Testing Codelab - No java

### ISSUE THREAD

**Issue by mosazaid** [googlecodelabs/android-testing#126]
Hi , 
thanks for your effort , i had been training in the steps with java but now i can't find find the steps in java, and it's just in kotlin , so please if you can set version steps for java and another for kotlin it would be great , 
but now it seems that the java tutorial is deleting or replace it with kotlin 
thank you

**Comment by febs** [comment]
Java for Android is dead mate.

**Comment by JoseAlcerreca** [comment]
It's not dead :) But we can't maintain two codebases and we chose Kotlin because the vast majority of devs prefer it. The testing concepts apply to Java, as well as the project configuration and Android Studio setup.

**Comment by mosazaid** [comment]
ok good point , i am now learning kotlin to get back to the Codelab UItest .. 
thanks for your efforts
