### ISSUE TITLE
Is there a finished version of this CodeLab?

### ISSUE THREAD

**Issue by mrk-han** [googlecodelabs/android-testing#129]
I want to be able to browse and experiment with a finished version, ideally this version would contain excellent code comments if possible :) 

I thought I had seen one earlier, but maybe I am mistaken.

**Comment by JoseAlcerreca** [comment]
You are right, we removed the solution branch because it was hard to maintain two at the same time.

If you look at the bottom of each file with a codelab exercise, you'll find methods with "_solution" in the name.

**Comment by mrk-han** [comment]
Ahh, I understand. Thank you @JoseAlcerreca.
