### ISSUE TITLE
Add an example of configuring a simulated device in a robolectric environment

### ISSUE THREAD

**Issue by jzbrooks** [googlecodelabs/android-testing#137]
Robolectric provides [`@Config`](https://github.com/robolectric/robolectric/blob/master/annotations/src/main/java/org/robolectric/annotation/Config.java) to facilitate simulated device configuration. 

As far as I can tell, there is no equivalent in the AndroidX test system.

We're trying to move in a direction where our ui tests can run either on device or in a simulated environment via espresso and Robolectric. However, our tests fail on a Robolectric environment because some of our views are drawn with less than 90% of the view on the screen. We don't target mdpi or super small screen size devices at all. Our tests (the same code) all pass on-device using a Pixel 2 emulator.

This might be a limitation in the framework. If so, I'd be happy to create another issue elsewhere. It seems like an important piece of the Nitrogen vision.

**Comment by JoseAlcerreca** [comment]
Not related to codelabs
