### ISSUE TITLE
Wrong method name in code of lesson 10

### ISSUE THREAD

**Issue by IevgenOsetrov** [googlecodelabs/android-testing#140]
In project code we have
`@Before
fun init() {
        repository = ServiceLocator.provideTasksRepository(getApplicationContext())
        repository.deleteAllTasksBlocking()
    }`
and in lesson 10 description we have
`@Before
fun resetState() {
    repository = ServiceLocator.provideTasksRepository(getApplicationContext())
}`

Please change method name "resetState" to "init"

**Comment by JoseAlcerreca** [comment]
This was alraedy fixed, if you're referring to codelab 5.3 - Step 9: Use Idling Resources in tests
