### ISSUE TITLE
[Documentation update required- TaskDetailViewModel is part of TaskDetailFragment & not TasksFragment] - Testing Codelab 5.2, Step 3 - Also Update TaskDetail Fragment and ViewModel

### ISSUE THREAD

**Issue by rutulkotak** [googlecodelabs/android-testing#157]
**Describe the problem**
Point-4: Update TasksFragment to use the factory.
TaskDetailFragment has TaskDetailViewModel & not TasksFragment
It should be "TaskDetailFragment" and not "TasksFragment"

**In which lesson and step of the codelab can this issue be found?**
Lesson number-5.2 + step number-3
https://codelabs.developers.google.com/codelabs/advanced-android-kotlin-training-testing-test-doubles/#6

**How to reproduce?**
Please have a look @ "Point-4: Update TasksFragment to use the factory."

**Versions**
1. What version of Android Studio are you using?
3.6.1

**Additional information**

**codelab:** advanced-android-kotlin

**Comment by JoseAlcerreca** [comment]
Looks fixed?
