### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.1, Task 8, Step 5 - Typo in a link

### ISSUE THREAD

**Issue by Abed-Murad** [googlecodelabs/android-testing#160]
**Describe the problem**
There is a type in the link that sends to **ApplicationProvider.getApplicationContext()**

 it looks like this:
>[ApplicationProvider.getApplicationContex t](https://developer.android.com/reference/androidx/test/core/app/ApplicationProvider.html#getApplicationContext()) 

while it should look like this: 
> [`ApplicationProvider.getApplicationContext()`](https://developer.android.com/reference/androidx/test/core/app/ApplicationProvider.html#getApplicationContext())

**In which lesson and step of the codelab can this issue be found?**

-> Advanced Android in Kotlin **05.1**
-> ->**Task 8.**(Setting up a ViewModel Test with AndroidX Test)
-> -> ->**Step 5.** Use AndroidX Test

**codelab:** advanced-android-kotlin

**Comment by JoseAlcerreca** [comment]
Thanks, fixed in next release.
