### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.#, Step # - Issue description

### ISSUE THREAD

**Issue by Pekwerike** [googlecodelabs/android-testing#161]
**Describe the problem**
The link to 5.1 Testing Basics codelabs is redirecting to custom view codelabs

**In which lesson and step of the codelab can this issue be found?**
5.2, Step 2

**How to reproduce?**
When you get to step 2 in the Test doubles and dependency injection codelabs, in the app overview section click on the 5.1 Testing basics link

**Versions**
1. What version of Android Studio are you using?

**Additional information**

**codelab:** advanced-android-kotlin

**Comment by JoseAlcerreca** [comment]
Fixed thanks
