### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.1, Step 4 - ( ) - parentheses missing after method name in Codelab sample code

### ISSUE THREAD

**Issue by CsiszerTamas** [googlecodelabs/android-testing#163]
**Describe the problem**

( )  - parentheses missing after method name of getActiveAndCompletedStats_noCompleted_returnsHundredZero in the sample code (in codelab)

**In which lesson and step of the codelab can this issue be found?**
Advanced Android in Kotlin 05.1: Testing Basics
Step 4: Use Hamcrest to write assertions

**How to reproduce?**

What are the exact steps to reproduce the problem?
Problem is in sample code in the codelab

**Versions**
1. What version of Android Studio are you using?

Android Studio 3.6.3
Build #AI-192.7142.36.36.6392135, built on April 14, 2020
Runtime version: 1.8.0_212-release-1586-b04 amd64

**Additional information**

**codelab:** advanced-android-kotlin

**Comment by JoseAlcerreca** [comment]
Thanks, fixed in next release.
