### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.2, Task 4, Step 3. - Returning wrong value

### ISSUE THREAD

**Issue by CsiszerTamas** [googlecodelabs/android-testing#164]
**Describe the problem**

`override suspend fun getTasks(): Result<List<Task>> {
    tasks?.let { return Success(ArrayList(it)) }
    return Error(
        Exception("Tasks not found")
    )
}`

In place of returning Error, we should return : **Result.Error(Exception("Tasks not found")**

` override suspend fun getTasks(): Result<List<Task>> {
        tasks?.let { return Result.Success(ArrayList(it)) }
        return Result.Error(
                Exception("Tasks not found")
        )
    }`

**In which lesson and step of the codelab can this issue be found?**

Advanced Android in Kotlin 05.2
4. Task: Make a Fake Data Source
Step 3: Implement the getTasks method in FakeDataSource

**How to reproduce?**
Problem is in codelab documentation 

**Versions**
1. What version of Android Studio are you using?

Android Studio 3.6.3
Build #AI-192.7142.36.36.6392135, built on April 14, 2020
Runtime version: 1.8.0_212-release-1586-b04 amd64

**Additional information**

**codelab:** advanced-android-kotlin

**Comment by JoseAlcerreca** [comment]
Looks like you just have to import the correct Error.
