### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.2, Task 7, Step 3 - The codelab says that "4. Update TasksFragment to use the factory." in TasksFragment.kt, but it should be saying that in TaskDetailFragment.kt

### ISSUE THREAD

**Issue by CsiszerTamas** [googlecodelabs/android-testing#165]
**Describe the problem**
A clear and concise description of what the problem is.

The codelab says that "4. Update TasksFragment to use the factory." in **TasksFragment.kt**, but it should be saying that in `TaskDetailFragment.kt`

`// REPLACE
private val viewModel by viewModels<TaskDetailViewModel>()
// WITH
private val viewModel by viewModels<TaskDetailViewModel> {
    TaskDetailViewModelFactory(DefaultTasksRepository.getRepository(requireActivity().application))
}`

**In which lesson and step of the codelab can this issue be found?**

Advanced Android in Kotlin 05.2: Introduction to Test Doubles and Dependency Injection
7. Task: Use the Fake Repository inside a ViewModel
Step 3. Also Update TaskDetail Fragment and ViewModel

**How to reproduce?**

Problem in codelab step description

**Versions**
1. What version of Android Studio are you using?

Android Studio 3.6.3
Build #AI-192.7142.36.36.6392135, built on April 14, 2020
Runtime version: 1.8.0_212-release-1586-b04 amd64

**Additional information**

**codelab:** advanced-android-kotlin

**Comment by georgetsiga** [comment]
I Agree there was a typo there.

**Comment by JoseAlcerreca** [comment]
Looks like #181
