### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.1, Step 10 

### ISSUE THREAD

**Issue by viftimie** [googlecodelabs/android-testing#167]
at 10. Task: Writing multiple ViewModel tests

It says: 
"Warning
Do not do the following, do not initialize the
tasksViewModel
with its definition:
val tasksViewModel = TasksViewModel(ApplicationProvider.getApplicationContext())
This will cause the same instance to be used for all tests."

The last statement is FALSE
Having the tasksViewModel instantiated directly there will NOT cause "the same instance to be used for all tests"
Sure, the correct approach IS to instantiate tasksViewModel in method with @Before.
-> So just remove the 3 lines with the warning & leave just the correct way.

Explanation:
Each @Test method is executed on a new instance of the class (this is the way jUnit makes sure each method is tested in isolation)
So for each @Test method, order is: 
- new instance of class (to prove: add a log in init{})
- @Before method (on this instance)
- @Test method (on this instance)
To prove the instances are not the same - use: System.identityHashCode(x)

**Comment by JoseAlcerreca** [comment]
Thanks, fixed in next release.
