### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.2#, Step 9# - Wrong title on snippet

### ISSUE THREAD

**Issue by buildbro** [googlecodelabs/android-testing#169]
**Describe the problem**
Code snippet with heading referring to the wrong file (TasksFragment.kt)

**In which lesson and step of the codelab can this issue be found?**
Lesson 9 + step 2.6
![Screen Shot 2020-05-27 at 5 38 41 PM](https://user-images.githubusercontent.com/16970059/83048149-10006080-a041-11ea-9f59-90a4b66a4201.png)
.

**How to reproduce?**
What are the exact steps to reproduce the problem?

**Versions**
1. What version of Android Studio are you using?

**Additional information**

**codelab:** advanced-android-kotlin

**Comment by JoseAlcerreca** [comment]
#223

**Comment by hirokihokari** [comment]
@JoseAlcerreca what is this ninja trick? Did you close both issues because one is a duplicate of the other?

**Comment by JoseAlcerreca** [comment]
No, it's fixed internally but I thought "nobody is going to check between the time I mark them as fixed and the time they're out" but I underestimated you.

**Comment by hirokihokari** [comment]
@JoseAlcerreca sorry for jumping to a conclusion. Understood. Thank you for the contribution.
