### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.#, Step # - Issue description

### ISSUE THREAD

**Issue by FAVOUR** [googlecodelabs/android-testing#170]
**Describe the problem**
I noticed a typo error 

**In which lesson and step of the codelab can this issue be found?**
(ex. 05.1, Step 2)

**How to reproduce?**
Third bullet point under the "Notice that test" statement 

"u8sually contain assertion statements."

 instead of 

usually contain assertion statements.

**codelab:** advanced-android-kotlin

**Comment by JoseAlcerreca** [comment]
#206
