### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.1, Step 2 - Wrong Function Name

### ISSUE THREAD

**Issue by yerenutku** [googlecodelabs/android-testing#171]
**Describe the problem**
There is a typo in the content. The function name stated as`getOrAwaitNextValue` however the function name is `getOrAwaitValue`

Full text is as follows: 
> You check that the tasksAddViewVisible is true, using the getOrAwaitNextValue method.

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number. (ex. 5.2, Step 7)
Lesson: 05.1,  Step 2

**How to reproduce?**
The typo would be shown each time Step 2 has displayed. 

**codelab:** advanced-android-kotlin

**Comment by JoseAlcerreca** [comment]
dup #236
