### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.#, Step # - Issue description

### ISSUE THREAD

**Issue by lsteamer** [googlecodelabs/android-testing#172]
**Describe the problem**
Typo

**In which lesson and step of the codelab can this issue be found?**
Advanced Android in Kotlin 05.1: Testing Basics
https://codelabs.developers.google.com/codelabs/advanced-android-kotlin-training-testing-basics/#4

**Additional information**
Notice that tests

- are a class in one of the test source sets.
- contain functions that start with the @Test annotation (each function is a single test).
- **u8sually** contain assertion statements.

**Comment by JoseAlcerreca** [comment]
#206
