### ISSUE TITLE
Saved Tasks are Deleted when the application is reopened

### ISSUE THREAD

**Issue by shrishkukde** [googlecodelabs/android-testing#175]
Hi Team,

When I save a task, it works fine till the app is opened in the foreground.
But as soon as we re-start the app all the new tasks are wiped out and only the following two tasks are present.
1. Build tower in Pisa
2. Finish bridge in Tacoma

If the tasks are not saved ten why we have implemented Room Database.
Please suggest.

**Comment by sku0x20** [comment]
@shrishkukde It is implemented to work like this only, please check the TasksRemoteDataSource file, and TasksViewModel.

**Comment by shrishkukde** [comment]
@siddhantkumar20 : Could you please explain this in detail. It will be really helpful to understand

**Comment by JoseAlcerreca** [comment]
That's for simplicity. It's a design decision from the very beginning which in hindsight was wrong. The Remote data source starts clean, so it cleans the local data source.
