### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.2, Step 3.4 - Task: Use the Fake Repository inside a ViewModel

### ISSUE THREAD

**Issue by haitanle** [googlecodelabs/android-testing#176]
**Describe the problem**
In the step 3.4- "Update TasksFragment to use the factory." I got an error when I perform the updates. 

**In which lesson and step of the codelab can this issue be found?**
5.2, Step 7

**How to reproduce?**
I got a compile error when made the code change update. 

**Versions**
1. What version of Android Studio are you using? Android Studio 3.6.1

**Additional information**
In step 1.4, there was already instruction to update ether TasksFragment.kt 

**codelab:** advanced-android-kotlin

**Comment by JoseAlcerreca** [comment]
Looks #181
