### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.7, Solution - Syntactical Mistake

### ISSUE THREAD

**Issue by karanjhinga** [googlecodelabs/android-testing#178]
**Describe the problem**
The solution provided at the end of task 5.7 has parenthesis missing for the first function

**In which lesson and step of the codelab can this issue be found?**
5.7

**How to reproduce?**
Go have a look

**Versions**
Doesn't matter

**codelab:** advanced-android-kotlin

**Comment by JoseAlcerreca** [comment]
In which codelab? There are three

5.1 Testing Basics
5.2 Dependency Injection and Test Doubles
5.3 Survey of Testing Topics

**Comment by karanjhinga** [comment]
Link to the page: https://codelabs.developers.google.com/codelabs/advanced-android-kotlin-training-testing-basics/index.html?index=..%2F..index#6

Scroll to almost 70% of the page and you find below heading **Solution: Writing more tests**, there's a code snippet of **StatisticsUtilsTest.kt** class. In this code snippet parenthesis are missing for the first test function.

Adding screenshot : [code snippet screenshot](https://i.ibb.co/9r0twWb/Capture.png)

**Comment by JoseAlcerreca** [comment]
Thanks, fixed in next release.
