### ISSUE TITLE
dagger2

### ISSUE THREAD

**Issue by cpeppas** [googlecodelabs/android-testing#18]
I have forked this project and created a new branch using dagger2. 
See here
https://github.com/cpeppas/android-testing/tree/dagger

I thought this might be useful because dagger2 is becoming very popular nowadays.

Because of the fact that I cannot do a PL of a new branch that does not exist on the original project that's why I am raising this as an issue

Let me know if you think it is somehow valuable so I can do a PL in some way.

**Comment by slinzner** [comment]
Thanks! This is really interesting
