### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.1, Step 2 - Issue description

### ISSUE THREAD

**Issue by JoysonF** [googlecodelabs/android-testing#180]
**Describe the problem**
Incorrect spelling of usually. Its typed as "u8ually".

**In which lesson and step of the codelab can this issue be found?**
Lesson Number :  05.1 + Step number : 2
**codelab:** advanced-android-kotlin

**Comment by JoseAlcerreca** [comment]
Thanks, fixed in next release.
