### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.2, Step 7 - Issue description

### ISSUE THREAD

**Issue by graffiti75** [googlecodelabs/android-testing#181]
**Link of the Codelab**
https://codelabs.developers.google.com/codelabs/advanced-android-kotlin-training-testing-test-doubles/index.html?index=..%2F..index#6

**Describe the problem**
Wrong description of text on item 7.3.4 of this Codelab.
- Advanced Android in Kotlin 05.2: Introduction to Test Doubles and Dependency Injection
	- 7 . Task: Use the Fake Repository inside a ViewModel
	- Step 3. Also Update TaskDetail Fragment and ViewModel
	- 4 . Update TasksFragment to use the factory.

**In which lesson and step of the codelab can this issue be found?**
Lesson number 7 + step number 3.4.

**How to reproduce?**
At item 7.3.4, the current description is:
"Update `TasksFragment` to use the factory."

The correct description here should be the one below, because the file that is updated here it the `TaskDetailFragment.kt` and not the `TasksFragment.kt`.
"Update `TaskDetailFragment` to use the factory."

**codelab:** advanced-android-kotlin

**Comment by JoseAlcerreca** [comment]
This seems fixed
