### ISSUE TITLE
[Codelab Issue] Codelab 5.1, Step 10, wrong function called

### ISSUE THREAD

**Issue by m-i-n-a-r** [googlecodelabs/android-testing#182]
**Describe the problem**
The method called should be getOrAwaitValue(), not awaitNextValue() (which isn't even found since it doesn't exist)

**In which lesson and step of the codelab can this issue be found?**
5.1 step 10

**How to reproduce?**
Just compare the solution code and the code in the Codelab

**Versions**
4.0.1

**codelab:** advanced-android-kotlin

**Comment by devsparkles** [comment]
here is the link https://codelabs.developers.google.com/codelabs/advanced-android-kotlin-training-testing-basics/index.html?index=..%2F..index#9

**Comment by JoseAlcerreca** [comment]
dup #236
