### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.3.8, Step 3 - Typo: 'ActiivtySenarioRule'

### ISSUE THREAD

**Issue by cplyon** [googlecodelabs/android-testing#183]
**Describe the problem**
Text reads: "What about ActiivtySenarioRule?"

It should read: "What about ActivityScenarioRule?"

**In which lesson and step of the codelab can this issue be found?**
5.3.8 Step 3

**How to reproduce?**
Read the text in the green aside b.ox

**codelab:** advanced-android-kotlin

**Comment by JoseAlcerreca** [comment]
Thanks, fixed in next release.
