### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.3.8, Step 5 - Typo: 'CountingIldingResource'

### ISSUE THREAD

**Issue by cplyon** [googlecodelabs/android-testing#184]
**Describe the problem**
Text reads: "CountingIldingResource allows you to increment and decrement a counter such that..."
Should read: "CountingIdlingResource allows you to increment and decrement a counter such that..."

**In which lesson and step of the codelab can this issue be found?**
5.3.8, Step 5

**How to reproduce?**
See the text under the EspressoIdlingResource.kt snippet.

**codelab:** advanced-android-kotlin

**Comment by JoseAlcerreca** [comment]
Thanks, fixed in next release.
