### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.3.9, Step 2 - Syntax error in AppNavigationTest.kt code snippet: "activityScenario.close()."

### ISSUE THREAD

**Issue by cplyon** [googlecodelabs/android-testing#185]
**Describe the problem**
The AppNavigationTest.kt code snippet users are asked to copy and paste contains syntax errors. Specifically, two of the calls to activityScenario.close() contain an extraneous period ("activityScenario.close().") The code is in taskDetailScreen_doubleUpButton() and taskDetailScreen_doubleBackButton()

**In which lesson and step of the codelab can this issue be found?**
5.3.9, Step 2

**How to reproduce?**
Copy and paste the code from the AppNavigationTest.kt snippet. Compilation will fail with "Expecting an element"

**codelab:** advanced-android-kotlin

**Comment by JoseAlcerreca** [comment]
Thanks, fixed in next release.
