### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.#, Step # - Issue description

### ISSUE THREAD

**Issue by kolanse** [googlecodelabs/android-testing#188]
**Describe the problem**

The first function does not have a "()" as illustrated below
```
@Test
    fun getActiveAndCompletedStats_noCompleted_returnsHundredZero {
        val tasks = listOf(
            Task("title", "desc", isCompleted = false)
        )
        // When the list of tasks is computed with an active task
        val result = getActiveAndCompletedStats(tasks)

        // Then the percentages are 100 and 0
        assertThat(result.activeTasksPercent, `is`(100f))
        assertThat(result.completedTasksPercent, `is`(0f))
    }
```

**In which lesson and step of the codelab can this issue be found?**
Lesson 05:1 Step 7

**How to reproduce?**
Copying and pasting the code in android studio throws an error because of a lack of brackets immediately after the function name

**Comment by JoseAlcerreca** [comment]
Thanks, fixed in next release.
