### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.1 Testing Basics: Step 6 - Missing method parenthesis

### ISSUE THREAD

**Issue by Abhimanyu14** [googlecodelabs/android-testing#189]
**Describe the problem**
Missing parenthesis for function "getActiveAndCompletedStats_noCompleted_returnsHundredZero" at the end with the Hamcrest changes

**In which lesson and step of the codelab can this issue be found?**
Advanced Android in Kotlin 05.1: Testing Basics - Step 6

**How to reproduce?**
Issue in codelab docs : https://codelabs.developers.google.com/codelabs/advanced-android-kotlin-training-testing-basics/index.html?index=..%2F..index#5 

**Versions**
-

**Additional information**
-

**codelab:** advanced-android-kotlin
![Google Codelab Issue](https://user-images.githubusercontent.com/29737108/91938620-f6427980-ed11-11ea-8be9-2d2a6c6f9fee.png)

**Comment by JoseAlcerreca** [comment]
Thanks, fixed in next release.
