### ISSUE TITLE
7th step typo

### ISSUE THREAD

**Issue by dEn13L** [googlecodelabs/android-testing#19]
https://codelabs.developers.google.com/codelabs/android-testing/index.html?index=../../index#6

The 7th step has typo

**Launch NoteDetailActivity with an Intent extra parameter**
Edit the file `app/src/androidTestMock/java/.../notes/NoteDetailScreenTest.java` and comment in the method as you work through this section:

should be 

**Launch NoteDetailActivity with an Intent extra parameter**
Edit the file `app/src/androidTestMock/java/.../notedetail/NoteDetailScreenTest.java` and comment in the method as you work through this section:

**Comment by slinzner** [comment]
Fixed in the next release!
