### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.1 Testing Basics: Step 6 - assertEquals() parameters swapped

### ISSUE THREAD

**Issue by Abhimanyu14** [googlecodelabs/android-testing#190]
**Describe the problem**
Swapped expected and actual arguments

**In which lesson and step of the codelab can this issue be found?**
Advanced Android in Kotlin 05.1: Testing Basics - Steps 6

**How to reproduce?**
Docs issue.
Advanced Android in Kotlin 05.1: Testing Basics -> 6. Task: Writing your first test -> Step 2: Write your first test function -> 6. Check that result is what you expected, using assertions.

Code in docs : 
// Check the result
assertEquals(result.completedTasksPercent, 0f)
assertEquals(result.activeTasksPercent, 100f)

The first parameter of assertEquals() should be the expected value and the second parameter is the actual value,

Code should be : 
assertEquals(0f, result.completedTasksPercent)
assertEquals(100f, result.activeTasksPercent)

**Versions**
-

**Additional information**
-

**codelab:** advanced-android-kotlin

**Comment by JoseAlcerreca** [comment]
dup #241
