### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.1, Step 2 - TYPO

### ISSUE THREAD

**Issue by ChrisCrisis** [googlecodelabs/android-testing#191]
**Describe the problem**
There is a typo in "usually" (u8sually) in the following part:

    Notice that tests
    - are a class in one of the test source sets.
    - contain functions that start with the @Test annotation (each function is a single test).
    - u8sually contain assertion statements.

**In which lesson and step of the codelab can this issue be found?**
5.1, Step 2

**codelab:** advanced-android-kotlin

**Comment by JoseAlcerreca** [comment]
#206
