### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.1.8, Step 5 - Description Typo

### ISSUE THREAD

**Issue by tomislavhofman** [googlecodelabs/android-testing#194]
**Describe the problem**
![Screenshot 2020-09-11 at 12 18 46](https://user-images.githubusercontent.com/19726609/92911167-f2f17100-f428-11ea-9373-2ca711744d3d.png)
`ApplicationProvider.getApplicationContex` `t`

**In which lesson and step of the codelab can this issue be found?**
https://codelabs.developers.google.com/codelabs/advanced-android-kotlin-training-testing-basics/index.html?index=..%2F..index#7
Step 5

**codelab:** advanced-android-kotlin

**Comment by JoseAlcerreca** [comment]
Thanks, fixed in next release.
