### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.1.9, Step 3 - Typo

### ISSUE THREAD

**Issue by tomislavhofman** [googlecodelabs/android-testing#195]
**Describe the problem**
"getContentIfNoteHandled" should be "getContentIfNotHandled"
![Screenshot 2020-09-11 at 12 23 04](https://user-images.githubusercontent.com/19726609/92911857-8b87f100-f429-11ea-984a-b321c22615ec.png)

**In which lesson and step of the codelab can this issue be found?**
https://codelabs.developers.google.com/codelabs/advanced-android-kotlin-training-testing-basics/index.html?index=..%2F..index#8
Step 3

**codelab:** advanced-android-kotlin

**Comment by JoseAlcerreca** [comment]
Done thanks
