### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.1.13, Step N/A - Wrong hyperlink

### ISSUE THREAD

**Issue by tomislavhofman** [googlecodelabs/android-testing#196]
**Describe the problem**
![Screenshot 2020-09-11 at 12 25 38](https://user-images.githubusercontent.com/19726609/92912276-ea4d6a80-f429-11ea-9e9e-fc0a308d0524.png)
[Official Testing Sample](https://github.com/android/architecture-samples/commits/master)
Hyperlink should take the user to https://github.com/android/architecture-samples

**In which lesson and step of the codelab can this issue be found?**
https://codelabs.developers.google.com/codelabs/advanced-android-kotlin-training-testing-basics/index.html?index=..%2F..index#12
Right at the top, under

> 13. Learn more
> 
> Samples:
> - [Official Testing Sample](https://github.com/android/architecture-samples/commits/master) - This is the official testing sample, which is based off of the same TO-DO Notes app used here. Concepts in this sample go beyond what is covered in the three testing codelabs.

**codelab:** advanced-android-kotlin

**Comment by JoseAlcerreca** [comment]
Thanks, fixed in next release.
