### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.2.4, Step N/A - wrongly named class

### ISSUE THREAD

**Issue by tomislavhofman** [googlecodelabs/android-testing#197]
**Describe the problem**
`DefaultTaskRepository` should be `DefaultTasksRepository`

**In which lesson and step of the codelab can this issue be found?**
https://codelabs.developers.google.com/codelabs/advanced-android-kotlin-training-testing-test-doubles/#3
`DefaultTaskRepository` is mentioned 7 times on the page, while the class name is `DefaultTasksRepository`

**codelab:** advanced-android-kotlin

**Comment by JoseAlcerreca** [comment]
Fixed thanks
