### ISSUE TITLE
typo in step 6

### ISSUE THREAD

**Issue by ma-coretex** [googlecodelabs/android-testing#20]
there is a line that says:

> First we capture the callback in the captor, then we call it with an empty list of notes:

which is referring to this code:

`mLoadNotesCallbackCaptor.getValue().onNotesLoaded(NOTES);`

However `NOTES` is not an empty list. So either use the `EMPTY_NOTES` field in the code or change the description so that it refers to a list of notes rather than empty list of notes.

**Comment by slinzner** [comment]
Thanks, fixed!
