### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.3.4, Step 2 - Error running completeTask_dataAndSnackbarUpdated test

### ISSUE THREAD

**Issue by jeikenberg** [googlecodelabs/android-testing#200]
This is in Advanced Android in Kotlin 05.3: Survey of Testing Topics - Step 2.

After adding the proper dispatchers the lab says that when the test is ran it should pass, but it doesn't for me. I get an error:

Exception in thread "main @coroutine#3" kotlin.NotImplementedError: An operation is not implemented: Not yet implemented

I looked into this and found out that the completeTask method in FakeTestRepository was not implemented yet. I went back through the lessons and could not find a place that says to implement the completeTask method in FakeTestRepository. I did find a place where the completeTask method in the FakeAndroidTestRepository was implemented though. After implementing the completeTask method in FakeRepository with the same implementation from FakeAndroidTestRepository the test passed.

I am using Android Studio version 4.1

**Comment by JoseAlcerreca** [comment]
Thanks, fixed in the next release
