### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.#, Step # - Issue description

### ISSUE THREAD

**Issue by GuillaumeDgr** [googlecodelabs/android-testing#201]
**Describe the problem**
Missing "()" at "getActiveAndCompletedStats_noCompleted_returnsHundredZero" in code part "Solution: Writing more tests"

**In which lesson and step of the codelab can this issue be found?**
Advanced Android in Kotlin 05.1: Testing Basics in code part "Solution: Writing more tests"

**Comment by JoseAlcerreca** [comment]
Thanks, fixed in next release.
