### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.1, Step 5. Use AndroidX Test - Typing mistake

### ISSUE THREAD

**Issue by GuillaumeDgr** [googlecodelabs/android-testing#202]
**Describe the problem**
Strange " '' " in "ApplicationProvider.getApplicationContex``t" in Step 5. Use AndroidX Test

**In which lesson and step of the codelab can this issue be found?**
Advanced Android in Kotlin 05.1: Testing Basics

**Comment by JoseAlcerreca** [comment]
Thanks, fixed in next release.
