### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.2, Step 6 - Typo

### ISSUE THREAD

**Issue by ernest75** [googlecodelabs/android-testing#204]
**Describe the problem**
There's a typo, on step6.
...
For StatisticsViewModel and AddEditTaskViewModel, update the code that acquires the repository to use the repository from the TodoApplication.
**TasksFragment.kt** -> I think this shoud be removed
...

**In which lesson and step of the codelab can this issue be found?**
Advanced Android in Kotlin 05.2: Introduction to Test Doubles and Dependency Injection
Step 6

**Comment by JoseAlcerreca** [comment]
Done, thanks!
