### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.#, Step # - Issue description

### ISSUE THREAD

**Issue by PguOrange** [googlecodelabs/android-testing#205]
**Describe the problem**
Text error --> ApplicationProvider.getApplicationConte**x``t**, 

**In which lesson and step of the codelab can this issue be found?**
05.1 - Step 5. Use AndroidX Test

**How to reproduce?**
Go to the page and you will see the error

**codelab:** advanced-android-kotlin

**Comment by JoseAlcerreca** [comment]
Thanks, this is a known issue on the codelabs engine.

**Comment by JoseAlcerreca** [comment]
For the record this is happening in https://developer.android.com/codelabs/advanced-android-kotlin-training-testing-basics#7
