### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.#, Step # - Issue description

### ISSUE THREAD

**Issue by amakare1** [googlecodelabs/android-testing#207]
**Describe the problem**
import statement org.hamcrest.MatcherAssert.assertThat
is not used for assertEquals() method

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number. (ex. 5.2, Step 7)
Task 6, step 4

**How to reproduce?**
What are the exact steps to reproduce the problem?
import org.hamcrest.MatcherAssert.assertThat
is not recognized for assertEquals() method

**Versions**
1. What version of Android Studio are you using?
4.1.1

**Additional information**
<img width="509" alt="Screen Shot 2020-11-26 at 10 05 08 AM" src="https://user-images.githubusercontent.com/12764964/100372481-e49a0680-2fce-11eb-8cc8-594d0feb2677.png">

**codelab:** advanced-android-kotlin

**Comment by JoseAlcerreca** [comment]
Fixed
