### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.#, Step # - Issue description

### ISSUE THREAD

**Issue by ashrafi** [googlecodelabs/android-testing#208]
**Describe the problem**
A clear and concise description of what the problem is.

u8sually contain assertion statements. u8sually misspelled :-)

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number. (ex. 5.2, Step 7)
lesson 5 step 2.

**How to reproduce?**
What are the exact steps to reproduce the problem?
read

**Versions**
1. What version of Android Studio are you using?
4.2 15

**Additional information**

**codelab:** advanced-android-kotlin

**Comment by JoseAlcerreca** [comment]
Done thanks
