### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.any - Option Deprecated

### ISSUE THREAD

**Issue by stfmygod** [googlecodelabs/android-testing#210]
**Describe the problem**
The option 'android.enableUnitTestBinaryResources' is deprecated, when using Android Studio 3.3+

It comes like that in the starter code. I found a fix: 
in the gradle.proprieties file, the line  'android.enableUnitTestBinaryResources=true' should be deleted from the started code.

**In which lesson and step of the codelab can this issue be found?**
Lesson 5.1, any step. The issue is in the starter code 

**How to reproduce?**
What are the exact steps to reproduce the problem?

**Versions**
1. What version of Android Studio are you using?
4.1.1
**Additional information**

**codelab:** advanced-android-kotlin

**Comment by JoseAlcerreca** [comment]
Done
