### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.2, Step 9 - runBlockingTest should be replaced with runBlocking

### ISSUE THREAD

**Issue by elizacamber** [googlecodelabs/android-testing#211]
Codelab 5.2, Step 9 
The TaskDetailFragmentTest.kt in the codelab's code is using runBlockingTest. Since the class is under the androidTest package it needs to be replaced with the runBlocking method instead

**Versions**
Any

**Additional information**

**codelab:** advanced-android-kotlin

**Comment by Dannark** [comment]
No, it should not, it is correct to use `runBlockingTest`.  But for it to work, you should import the dependency **kotlinx coroutines test** for both `AndroidTest` and `Test` source set like bellow: 

```kotlin
androidTestImplementation "org.jetbrains.kotlinx:kotlinx-coroutines-test:$coroutinesVersion"
testImplementation "org.jetbrains.kotlinx:kotlinx-coroutines-test:$coroutinesVersion"
```

Check all the dependencies in app gradle [here](https://github.com/googlecodelabs/android-testing/blob/end_codelab_2/app/build.gradle)
