### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.2, Step 7 - 404 Page not found

### ISSUE THREAD

**Issue by stfmygod** [googlecodelabs/android-testing#213]
**Describe the problem**
All the links from the end of the page do not work.

**In which lesson and step of the codelab can this issue be found?**
5.2 step 7

**Additional information**
The projects were deleted or made private on github.

**codelab:** advanced-android-kotlin

**Comment by JoseAlcerreca** [comment]
dup #224
