### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.#, Step # - Issue description

### ISSUE THREAD

**Issue by Yan9080** [googlecodelabs/android-testing#214]
**Describe the problem**
Link is broken in "  (using the reactive architecture version of the sample) " 

**In which lesson and step of the codelab can this issue be found?**
Lesson 5: Testing and Dependency Injection + 
 05.1: Testing Basics +  
4. Task: Familiarizing yourself with the code +
Step 2: Explore the sample app code

**codelab:** advanced-android-kotlin

**Comment by JoseAlcerreca** [comment]
Thanks, fixed in next release.
