### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.#, Step # - Issue description

### ISSUE THREAD

**Issue by ashrafi** [googlecodelabs/android-testing#216]
**Describe the problem**
 @Test
    fun getActiveAndCompletedStats_noCompleted_returnsHundredZero {

should be 
 @Test
    fun getActiveAndCompletedStats_noCompleted_returnsHundredZero**()** {

**In which lesson and step of the codelab can this issue be found?**
step 4 

**How to reproduce?**
run the file.  Just need to add the "()"

**codelab:** advanced-android-kotlin

**Comment by JoseAlcerreca** [comment]
Thanks, fixed in next release.
