### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.1, Step 5 - Typos and formatting errors

### ISSUE THREAD

**Issue by bjoernwe** [googlecodelabs/android-testing#217]
**Describe the problem**
There are a few typos and formatting errors in the text.

In particular:

- Headline: **Local tests (**test source set)
- Headline: **Instrumented tests (**androidTest source set)
- Bullet point: u8sually [...]

**In which lesson and step of the codelab can this issue be found?**
In codelab **Advanced Android in Kotlin 05.1**, Step 5 ("Task: Running Tests")

**How to reproduce?**
Check [codelab](https://developer.android.com/codelabs/advanced-android-kotlin-training-testing-basics#4)

**Versions**
[not relevant]

**codelab:** advanced-android-kotlin

**Comment by JoseAlcerreca** [comment]
Thanks fixed in next release
