### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.1, Step 4 - Broken link in the anchor text "reactive architecture" 

### ISSUE THREAD

**Issue by 404set** [googlecodelabs/android-testing#218]
Broken link (404) to "https://github.com/android/architecture-samples/tree/reactive"

**Comment by Yan9080** [comment]
Yes, all of those links are broken :/
![Captura](https://user-images.githubusercontent.com/26819676/104832559-e4481a00-585f-11eb-97c3-2eec07b7137a.PNG)

**Comment by JoseAlcerreca** [comment]
All fixed
