### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.#, Step # - Issue description

### ISSUE THREAD

**Issue by isj0217** [googlecodelabs/android-testing#219]
**Describe the problem**
Typo catched
("u8sually")

**In which lesson and step of the codelab can this issue be found?**
5. Task: Running tests,
Step 2: Make the test fail

**How to reproduce?**
you can just delete typo "8" in "u8sually"

**Versions**
1. What version of Android Studio are you using?
4.1 I guess

**Additional information**

Thank you guys for developing tools and enlightening us

**codelab:** advanced-android-kotlin

**Comment by JoseAlcerreca** [comment]
#160
