### ISSUE TITLE
Step# 9 Test fails when device was setted up to Portuguese language

### ISSUE THREAD

**Issue by augustolf** [googlecodelabs/android-testing#22]
On Step# 9 the test AppNavigationTest#clickOnAndroidHomeIcon_OpensNavigation() fails if the device is not in English language (e.g. if the device's language was set to Portuguese, the content description will be "Navegar para cima" rather than "Navigate up").

![appnavigationtest_clickonandroidhomeicon_opensnavigation](https://cloud.githubusercontent.com/assets/617556/14283943/ac3b23ec-fb1b-11e5-876e-15430a26ff23.jpg)

**Comment by slinzner** [comment]
This was already fixed in https://github.com/googlecodelabs/android-testing/pull/15. Thanks for reporting this issue!
