### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.2, Step 9 - Wrong class name

### ISSUE THREAD

**Issue by dlqkfzlr** [googlecodelabs/android-testing#223]
**Describe the problem**
After Step2-6
'TasksFragment.kt' should be changed to 'StatisticsViewModel.kt' & 'AddEditTaskViewModel.kt'
(See the attatched file with a highlighted word)

**In which lesson and step of the codelab can this issue be found?**
5.2, Step 9
![bug_report](https://user-images.githubusercontent.com/44568146/106557658-9de40200-6565-11eb-9705-bee2fb705961.PNG)

**How to reproduce?**
What are the exact steps to reproduce the problem?

**Versions**
1. What version of Android Studio are you using?

**Additional information**

**codelab:** advanced-android-kotlin

**Comment by hirokihokari** [comment]
Duplicate #169
