### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.2, Step 7 - Iinks are dead

### ISSUE THREAD

**Issue by Krzysiudan** [googlecodelabs/android-testing#224]
**Describe the problem**
Links are dead

**In which lesson and step of the codelab can this issue be found?**
5.2 Step 7 - last tip on the bottom of the page

**Comment by tuvokian** [comment]
The relevant files linked should be:
https://github.com/android/architecture-samples/blob/main/app/src/main/java/com/example/android/architecture/blueprints/todoapp/ViewModelFactory.kt
and 
https://github.com/android/architecture-samples/blob/main/app/src/main/java/com/example/android/architecture/blueprints/todoapp/util/FragmentExt.kt

**Comment by JoseAlcerreca** [comment]
Fixed thanks
