### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.#, Step # - Issue description

### ISSUE THREAD

**Issue by miguelmanzo** [googlecodelabs/android-testing#226]
The first function is missing the parenthesis after in the function declaration:

At the moment it is : 
@Test
    fun getActiveAndCompletedStats_noCompleted_returnsHundredZero {
    
Should be: 
@Test
    fun getActiveAndCompletedStats_noCompleted_returnsHundredZero**()** {

**Comment by JoseAlcerreca** [comment]
Fixed in next release thanks
