### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.#, Step # - Issue description

### ISSUE THREAD

**Issue by wallenr** [googlecodelabs/android-testing#228]
**Describe the problem**
A clear and concise description of what the problem is.

A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.android.internal.application']
   > The option 'android.enableUnitTestBinaryResources' is deprecated.
     The current default is 'false'.
     It has been removed from the current version of the Android Gradle plugin.
     The raw resource for unit test functionality is removed.

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number. (ex. 5.2, Step 7)
5.1 step 5
**How to reproduce?**
Run the ExampleUnitTest
**Versions**
1. What version of Android Studio are you using?
Android Studio 4.1.2
**Additional information**

**codelab:** advanced-android-kotlin

**Comment by JoseAlcerreca** [comment]
Fixed already
