### ISSUE TITLE
"Android Instrumentation Tests"  is not anymore supported by Android Studio

### ISSUE THREAD

**Issue by afaucogney** [googlecodelabs/android-testing#23]
That's in the title

**Comment by jimandreas** [comment]
Looks like the tests are now enabled by default in Android Studio 2.0+.   Here is a snip from an answer by user markproxy on stackoverflow.com:

>  I discovered this in the release notes for Android Studio 2.0 Preview 5: "The experimental test artifacts feature (where both unit test and instrumentation tests are enabled simultaneously in the IDE) has been improved further and is now enabled by default."

See:
[http://stackoverflow.com/questions/35708263/test-artifact-selector-missing-gone-from-build-variants-in-android-studio-2-beta](http://stackoverflow.com/questions/35708263/test-artifact-selector-missing-gone-from-build-variants-in-android-studio-2-beta)

**Comment by slinzner** [comment]
This is fixed in the next release and will be included in the next codelab update which will be pushed soon!
