### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.1, Step 8 - What drawing software to use in Codelab

### ISSUE THREAD

**Issue by zhangkevd** [googlecodelabs/android-testing#230]
**Describe the problem**
What drawing software to use in Codelab?

![](https://developer.android.com/codelabs/advanced-android-kotlin-training-testing-basics/img/29aa6ed667e2fb1.png)

**Comment by zhangkevd** [comment]
![](https://developer.android.com/codelabs/advanced-android-kotlin-training-testing-test-doubles/img/ed5e6485d179c1b9.png)

**Comment by JoseAlcerreca** [comment]
Sorry I don't have this information
