### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.#, Step # - Issue description

### ISSUE THREAD

**Issue by ink404** [googlecodelabs/android-testing#231]
**Describe the problem**
Typo under step 2 
"u8sually contain assertion statements." should be "usually contain assertion statements."

**In which lesson and step of the codelab can this issue be found?**
5.1 step 2

**How to reproduce?**
N/A

**Versions**
N/A

**Additional information**
none

**codelab:** advanced-android-kotlin

**Comment by JoseAlcerreca** [comment]
Fixed thanks
