### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.#, Step # - Issue description

### ISSUE THREAD

**Issue by SojoC** [googlecodelabs/android-testing#232]
Build file 'C:\Users\Familia Sojo\Downloads\android-testing-starter_code\app\build.gradle' line: 1

A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.android.internal.application']
   > The option 'android.enableUnitTestBinaryResources' is deprecated.
     The current default is 'false'.
     It has been removed from the current version of the Android Gradle plugin.
     The raw resource for unit test functionality is removed.

**Comment by SojoC** [comment]
Tengo el siguiente problema en mi app:
Build file 'C:\Users\Familia Sojo\Downloads\android-testing-starter_code\app\build.gradle' line: 1

A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.android.internal.application']
   > The option 'android.enableUnitTestBinaryResources' is deprecated.
     The current default is 'false'.
     It has been removed from the current version of the Android Gradle plugin.
     The raw resource for unit test functionality is removed.
Ya actualice el gradle, y continua el problema, estoy usando android 4.1

**Comment by JoseAlcerreca** [comment]
Fixed
