### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.#, Step # - Issue description

### ISSUE THREAD

**Issue by marcodallaba** [googlecodelabs/android-testing#233]
**Describe the problem**
Typo in text: ApplicationProvider.getApplicationContex``t 
<img width="763" alt="Screenshot 2021-03-21 at 18 58 13" src="https://user-images.githubusercontent.com/22169710/111915598-6549aa80-8a77-11eb-9c6c-3fbd23237a5b.png">

**In which lesson and step of the codelab can this issue be found?**
05.1, Step 8

**codelab:** advanced-android-kotlin

**Comment by JoseAlcerreca** [comment]
Fixed in next release thanks
