### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.#, Step # - Issue description

### ISSUE THREAD

**Issue by jharnam** [googlecodelabs/android-testing#236]
**Describe the problem**
A clear and concise description of what the problem is.
Typo in code for "Your final code for TasksViewModelTest should look like the code below."
awaitNextValue() should have been getOrAwaitValue()

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number. (ex. 5.2, Step 7)
Advanced Android in Kotlin 05.1: Testing Basics
10. Task: Writing multiple ViewModel tests

**How to reproduce?**
What are the exact steps to reproduce the problem?
- Paste the code in section "Your final code for TasksViewModelTest should look like the code below." in the TasksViewModelTest.kt file
- Observe that the definition of awaitNextValue() is not found.

**Versions**
1. What version of Android Studio are you using?
4.1.1

**Additional information**

**codelab:** advanced-android-kotlin

**Comment by JoseAlcerreca** [comment]
Fixed in the next push of the content, thanks.
