### ISSUE TITLE
Codelab zip files show as encrypted on Windows 7

### ISSUE THREAD

**Issue by jimandreas** [googlecodelabs/android-testing#24]
Hi All,

Thanks very much for setting up this codelab for testing.   It is great!   One note - this was new to me.  The files in the zip file at the codelab download web page - when unpacked on a Windows 7 system - show as encrypted.  The zip file was downloaded from here:

[https://codelabs.developers.google.com/codelabs/android-testing/#1](https://codelabs.developers.google.com/codelabs/android-testing/#1)

Some filenames show in a green color in Windows Explorer, indicating that they are encrypted.   Evidently this is some interesting interaction where files encrypted on a Mac OS system are tagged with a bit that is confused by Windows as needing encryption.  My solution - I will switch to pulling the files for the code lab from github.   You can right click to Properties -> Advanced to clear the encryption status, but that is a hassle. :-)

Here is more info on the interesting interaction issue:

[https://blogs.msdn.microsoft.com/asklar/2012/05/03/why-do-zip-files-from-mac-os-show-up-as-greenencrypted/](https://blogs.msdn.microsoft.com/asklar/2012/05/03/why-do-zip-files-from-mac-os-show-up-as-greenencrypted/)

**Comment by slinzner** [comment]
We will certainly have a look at this when we generate zips going forward! Thanks for reporting this to us!
