### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.#, Step # - Issue description

### ISSUE THREAD

**Issue by Turskyi** [googlecodelabs/android-testing#242]
**Describe the problem**
Downloaded the project but it does not work.
TasksFragmentArgs, TasksFragmentDirections and many others classes are not existing.

**In which lesson and step of the codelab can this issue be found?**
Advanced Android in Kotlin 05.1: Testing Basics. Step 3.

**How to reproduce?**
Download the project archive and try to run it.

**Versions**
1. What version of Android Studio are you using?
4.1.3

**codelab:** advanced-android-kotlin

**Comment by JoseAlcerreca** [comment]
Build has been fixed for AS 4.2.1
