### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.2, Step 2 - typo in u8sually text

### ISSUE THREAD

**Issue by blasiusneri** [googlecodelabs/android-testing#246]
**Describe the problem**
typo in **u8sually** text

**In which lesson and step of the codelab can this issue be found?**
Lesson numbe 5 + step number. 2

**How to reproduce?**
-

**Versions**
-

**Additional information**
-

**codelab:** advanced-android-kotlin

**Comment by JoseAlcerreca** [comment]
#206
