### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.1, Step 9 - typo on getContentIfNoteHandled

### ISSUE THREAD

**Issue by blasiusneri** [googlecodelabs/android-testing#249]
**Describe the problem**
typo text getContentIfNoteHandled

**In which lesson and step of the codelab can this issue be found?**
Lesson number 5.1 + step number. 9

**How to reproduce?**
must be **getContentIfNotHandled**

**Versions**
1. What version of Android Studio are you using? 4.2

**Additional information**
-

**codelab:** advanced-android-kotlin

**Comment by JoseAlcerreca** [comment]
Didn't find the issue so it must have been fixed
