### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.#, Step 1 

### ISSUE THREAD

**Issue by LoganTylerPatterson** [googlecodelabs/android-testing#250]
**Describe the problem**
The app cant even build

**In which lesson and step of the codelab can this issue be found?**
Advanced Kotlin 5.01

**How to reproduce?**
Download your starter code and try to build it

**Versions**
4.2.1

**Additional information**
Cant even build the app, your dependencies are so old, tried updating them, also didnt work. This is something that is meant to educate and you cant get past step #1. When you cant even test in the tutuorial, this is why people hate android dev...

**codelab:** advanced-android-kotlin

**Comment by JoseAlcerreca** [comment]
This has been fixed for AS 4.2.1
