### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.#, Step # - Issue description

### ISSUE THREAD

**Issue by ManagedStudios** [googlecodelabs/android-testing#251]
**Describe the problem**
Build fails

**In which lesson and step of the codelab can this issue be found?**
5.1 step 1

**How to reproduce?**
run the starter code

**Versions**
Arctic Fox

**Additional information**

**codelab:** advanced-android-kotlin

**Comment by JoseAlcerreca** [comment]
This has been fixed for AS 4.2.1
