### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.#, Step # - Issue description

### ISSUE THREAD

**Issue by sah0017** [googlecodelabs/android-testing#252]
**Describe the problem**
A clear and concise description of what the problem is.
I am getting a compiler error when I try to run the code.

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number. (ex. 5.2, Step 7)
Task 4, step 1

**How to reproduce?**
What are the exact steps to reproduce the problem?
Clone code from git and try to run it.

**Versions**
1. What version of Android Studio are you using?
4.2.1

**Additional information**
![image](https://user-images.githubusercontent.com/1664398/120731659-aca5db80-c4a9-11eb-8968-838db00c6561.png)

**codelab:** advanced-android-kotlin

**Comment by JoseAlcerreca** [comment]
This has been fixed
