### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.1, Step 5 - Issue description

### ISSUE THREAD

**Issue by Dzendo** [googlecodelabs/android-testing#253]
**Describe the problem**
A clear and concise description of what the problem is.

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number. (ex. 5.2, Step 7)

**How to reproduce?**
What are the exact steps to reproduce the problem?

**Versions**
1. What version of Android Studio are you using?

**Additional information**

**codelab:** advanced-android-kotlin
Testing Codelab 5.1, Step 5
Android JUnit 3c8d5fb1cf5432ce.png
Android Instrumented Tests d49bf0424470dbba.png
In the figures to the text of the presentation, the icons are mixed up:
Android JUnit 3c8d5fb1cf5432ce.png  <----> Android Instrumented Tests d49bf0424470dbba.png
Only icons in *.png are mixed up, but text is right
Please fix it. Thanks

**Comment by JoseAlcerreca** [comment]
Sorry, I can't really understand what you mean. I checked the page and it seems correct. Can you reopen with a screenshot?
