### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.1, Step 10 - Issue description

### ISSUE THREAD

**Issue by bisverse** [googlecodelabs/android-testing#254]
**Describe the problem**
Final code for TasksViewModelTest at the end.
It should be 
`val value = tasksViewModel.newTaskEvent.getOrAwaitValue()
` 
`        assertThat(tasksViewModel.tasksAddViewVisible.getOrAwaitValue(), `is`(true))
`
instead of 

`val value = tasksViewModel.newTaskEvent.awaitNextValue()
`
`        assertThat(tasksViewModel.tasksAddViewVisible.awaitNextValue(), `is`(true))
`

**In which lesson and step of the codelab can this issue be found?**
Testing Codelab 5.1, Step 10

**How to reproduce?**
Get the code

**Versions**
1. Android Studio 4.1.2

**Additional information**
Possibly a typ

**codelab:** advanced-android-kotlin

**Comment by JoseAlcerreca** [comment]
dup #236
