### ISSUE TITLE
[Codelab Issue] Testing Codelab 5.#, Step # - Execution failed for task ':app:kaptDebugKotlin'.

### ISSUE THREAD

**Issue by begliamanov** [googlecodelabs/android-testing#282]
I get this error and tried to change JDK(currently using 11.0.11) to version 1.8 where I get a different error:

```
Execution failed for task ':app:kaptDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask$KaptExecutionWorkAction
   > java.lang.reflect.InvocationTargetException (no error message)

```
**Android Studio** (Apple Chip version): Bumblebee 2021.1.1 Patch 3

**Comment by begliamanov** [comment]
I get the error on build

**Comment by joec58** [comment]
Build failed for me too. Maybe a related problem.

Ubuntu Android Studio Dolphin | 2021.3.1 Canary 7
Updated `build.gradle` project and app dependencies:

```
:app:kaptDebugKotlin
TasksListBindingsKt.java
Application namespace for attribute app:items will be ignored.
Application namespace for attribute app:completedTask will be ignored.
:app:compileDebugKotlin
AddEditTaskFragmentDirections.kt
Unresolved reference: R
Unresolved reference: R
StatisticsFragmentDirections.kt
Unresolved reference: R
Unresolved reference: R
TaskDetailFragmentDirections.kt
Unresolved reference: R
Unresolved reference: R
Unresolved reference: R
TasksFragmentDirections.kt
Unresolved reference: R
Unresolved reference: R
Unresolved reference: R
Unresolved reference: R
```

**Comment by phamngoc285** [comment]
> I get this error and tried to change JDK(currently using 11.0.11) to version 1.8 where I get a different error:
> 
> ```
> Execution failed for task ':app:kaptDebugKotlin'.
> > A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask$KaptExecutionWorkAction
>    > java.lang.reflect.InvocationTargetException (no error message)
> ```
> 
> **Android Studio** (Apple Chip version): Bumblebee 2021.1.1 Patch 3

To me, changing the roomVersion to '2.4.2' solved the issue.

**Comment by begliamanov** [comment]
Thank you, @phamngoc285! changing roomVersion to '2.4.2' worked for me too.

**Comment by vrsrohit** [comment]
Changing the Room version to 2.4.2 worked for me too 
Thanks, @phamngoc285
