### ISSUE TITLE
Typo in Chapter 7, 8, 9

### ISSUE THREAD

**Issue by egor-n** [googlecodelabs/android-testing#3]
The following text is duplicated right at the beginning of Chapter 7, 8 and 9:
> If you would like to start fresh for this section, continue from snapshot ‘step-7/8/9’:

**Comment by slinzner** [comment]
This is WAI, we just want to point out that we created some step branches which make your life easier if you want to start over.

**Comment by egor-n** [comment]
I meant that the text is typed out two times. This is what I see in Chapter 7:

![](http://i.imgur.com/FnB0Q7C.png?1)
