### ISSUE TITLE
Wrong link in "JUnit test rules" (step 7)

### ISSUE THREAD

**Issue by AlbertVilaCalvo** [googlecodelabs/android-testing#45]
Hi. In step 7 the following sentence:

> JUnit test rules allow the alteration of test methods. It is run before any test...

Contains a link in the words "JUnit test rules" which points to http://junit.org/apidocs/org/junit/rules/TestRule.html. This website gives a 404 now. The URL should be updated.

**Comment by jimandreas** [comment]
Looks like this link is a decent replacement on the topic, for what it is worth:

[http://junit.org/junit4/javadoc/latest/org/junit/rules/TestRule.html](http://junit.org/junit4/javadoc/latest/org/junit/rules/TestRule.html)

**Comment by slinzner** [comment]
Thanks fixed! Will be available in the next release.
