### ISSUE TITLE
Step 5 references the NotesPresenter object in a different method.

### ISSUE THREAD

**Issue by anyercastillo** [googlecodelabs/android-testing#47]
https://codelabs.developers.google.com/codelabs/android-testing/index.html?index=..%2F..%2Findex#4

In the section `Creating the NotesPresenter`
The NotesPresenter object  is created in `onCreate(...)` instead of `onActivityCreated(...)`

Thank you.

**Comment by jfschmakeit** [comment]
Dupe of issue #68 . Fixed in the next doc release.
