### ISSUE TITLE
Step 6 contains a broken link

### ISSUE THREAD

**Issue by anyercastillo** [googlecodelabs/android-testing#48]
https://codelabs.developers.google.com/codelabs/android-testing/index.html?index=..%2F..%2Findex#5

In the section `Mocking dependencies with Mockito`
The link for the `ArgumentCaptor` documentation is broken.

- broken link: http://docs.mockito.googlecode.com/hg/1.9.5/org/mockito/ArgumentCaptor.html
- GitHub: https://github.com/mockito/mockito/blob/master/src/main/java/org/mockito/ArgumentCaptor.java

Thank you.

**Comment by slinzner** [comment]
Thanks fixed, will be available in next codelab release.
