### ISSUE TITLE
New Gradle sync icon in Android Studio 2.2+

### ISSUE THREAD

**Issue by richarth** [googlecodelabs/android-testing#49]
In [step 6](https://codelabs.developers.google.com/codelabs/android-testing/index.html?index=..%2F..%2Findex#5) there is a section 'Optionally sync your project'.  With this section there is a line of text showing the button to sync Gradle.

This button icon has changed in Android Studio 2.2 so it might be worth showing both icons.

**Comment by jfschmakeit** [comment]
Thanks, I have updated the icon for the next release.
