### ISSUE TITLE
IncompatibleClassChangeError

### ISSUE THREAD

**Issue by rhespanhol** [googlecodelabs/android-testing#5]
When running the first espresso test from step 7 i got this error:

java.lang.IncompatibleClassChangeError: com.example.android.testing.notes.notes.NotesActivity

the only way i was able to fix it was to include in the gradle file:
    androidTestCompile ("com.android.support.test.espresso:espresso-contrib:$rootProject.ext.espressoVersion") {
        exclude group: 'com.android.support', module: 'appcompat'
        exclude group: 'com.android.support', module: 'support-v4'
        exclude module: 'recyclerview-v7'
    }

Am i doing something wrong?

Btw, great codelab :)

**Comment by slinzner** [comment]
Thanks, no you don't i committed a fix to the master branch yesterday to fix this until a tools bug is resolved! I will cherry pick the master changes into the step branches today or tomorrow. I update this issue once that's done...

**Comment by slinzner** [comment]
This was fixed in the codelab for 1.5. But the ultimate fix for correct handling of transitive deps in the Gradle Android Plugin directly was released in version 2.0.0-alpha1
