### ISSUE TITLE
Default build variant is set to mockDebug

### ISSUE THREAD

**Issue by farmazon3000** [googlecodelabs/android-testing#50]
I'm following the tutorial https://codelabs.developers.google.com/codelabs/android-testing/index.html. I've cloned the repo, imported code to Android Studio, run 'app' and ... it does not work (it starts but add note button does nothing).

I realized that Android Studio built the mockDebug version while it should build prodDebug.

**Comment by slinzner** [comment]
Which step are you looking at? The app should work in both mockDebug/prodDebug flavors, unless you are using one of the step branches other than final, which might not have the desired functionality yet.

**Comment by farmazon3000** [comment]
I think it was step 2 - anyway, the real cause of this issue was #51, i.e. app was planned not to work in step 2. Closing.
