### ISSUE TITLE
We are getting a blank screen with no notes or working buttons

### ISSUE THREAD

**Issue by farmazon3000** [googlecodelabs/android-testing#51]
I'm following the tutorial
https://codelabs.developers.google.com/codelabs/android-testing/index.html

I see that in step 5 it's mentioned
https://codelabs.developers.google.com/codelabs/android-testing/index.html?index=..%2F..%2Findex#4
`If you have run the app already, you will have noticed that we are getting a blank screen with no notes or working buttons!`
Please move this information to step 2.

**Comment by farmazon3000** [comment]
OK, I see that it's mentioned in step 5
https://codelabs.developers.google.com/codelabs/android-testing/index.html?index=..%2F..%2Findex#4
`If you have run the app already, you will have noticed that we are getting a blank screen with no notes or working buttons!`
Please move this information to step 2.

**Comment by slinzner** [comment]
Fixed in next codelab release
