### ISSUE TITLE
Step 7 batch test status screen is wrong

### ISSUE THREAD

**Issue by farmazon3000** [googlecodelabs/android-testing#53]
In section 7 there is:
`Their status is displayed in the Run Panel that opened at the bottom of the screen:`
and there is an image https://codelabs.developers.google.com/codelabs/android-testing/img/391e5d4c2d01e584.png where `clickAddNoteButton_opensAddNoteUi` is green but I think at this step it should be red (it's on my machine) so the image is misleading.

**Comment by efung** [comment]
I think that screenshot is appropriate. In the section "Espresso Test 1: Opening the ‘Add Note' screen", they describe that test. You're meant to comment out any `fail()` lines and uncomment the test code if your copy doesn't match that.

**Comment by jfschmakeit** [comment]
Yes, I agree with @efung  - you are implementing this test a little earlier in step 7 and at this point the test should no longer fail.
