### ISSUE TITLE
Prefer  usage of @Rule public MockitoRule rule = MockitoJUnit.rule() over MockitoAnnotations.initMocks(this);

### ISSUE THREAD

**Issue by vogella** [googlecodelabs/android-testing#55]
IMHO the usage of  @Rule public MockitoRule rule = MockitoJUnit.rule(); is much nicer, compared to MockitoAnnotations.initMocks(this);

You should update your NotesPresenterTest

**Comment by JoseAlcerreca** [comment]
Revamped the whole codelab and we removed almost all mocks.
