### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by jaredsburrows** [googlecodelabs/android-testing#56]
@slinzner Could we add TravisCI so users can see a working example of espresso?

**Comment by santhoshvai** [comment]
TravisCI with android emulators are memory intensive and mostly an outOfMemory exception occurs.

**Comment by jaredsburrows** [comment]
@santhoshvai That's not true at all. Have you ever setup travisci with emulators?

Working Examples:
https://github.com/JakeWharton/butterknife/blob/master/.travis.yml#L16
https://github.com/jaredsburrows/android-bloatware/blob/master/.travis.yml#L14

**Comment by santhoshvai** [comment]
@jaredsburrows yes I have. I know that there are working examples. Thanks for linking them. But when you use libraries with many methods like guava it fails. Personal experience. Here they include guava. It may work too, we could try.

**Comment by jaredsburrows** [comment]
@santhoshvai Please share an open source example where an emulator fails because of guava. I am guessing you are over the single dex limit?

**Comment by santhoshvai** [comment]
@jaredsburrows  yes multidex.

**Comment by jaredsburrows** [comment]
Then allocate more memory to the Travis build:
https://github.com/jaredsburrows/android-gif-example/blob/master/.travis.yml#L5
.

Jared Burrows

*jaredsburrows@gmail.com <jaredsburrows@gmail.com>*
LinkedIn: https://www.linkedin.com/in/jaredsburrows

**Comment by santhoshvai** [comment]
Thanks!

**Comment by santhoshvai** [comment]
I tested the travis config from jared. It works!. It would be great to add a travis config here.

**Comment by JoseAlcerreca** [comment]
Added in https://github.com/googlecodelabs/android-testing/commit/be7bef15c116d95230588e94bfe986cf39df6a67
