### ISSUE TITLE
Page 9 link is broken

### ISSUE THREAD

**Issue by yukuku** [googlecodelabs/android-testing#58]
Link to https://github.com/googlecodelabs/android-testing/blob/master/app/src/androidTest/java/com/example/android/testing/notes/custom/action/NavigationViewActions.java is broken, probably because NavigationViewActions is now part of espresso-contrib, no longer part of Notes.

**Comment by jfschmakeit** [comment]
I just had a quick - you are correct, this has been merged into espresso-contrib. I'll update the documentation.

See:  https://developer.android.com/reference/android/support/test/espresso/contrib/NavigationViewActions.html

**Comment by jfschmakeit** [comment]
I have fixed this for the next document release.
