### ISSUE TITLE
Step 9 clickOnAndroidHomeIcon_OpensNavigation test successful showing wrong image.

### ISSUE THREAD

**Issue by jeikenberg** [googlecodelabs/android-testing#59]
At the section that shows the pass fail of the clickOnAndroidHomeIcon_OpensNavigation test, the image shows the clickOnAndroidHomeIcon_OpensNavigation failing and the clickOnStatisticsNavigationItem_ShowsStatisticsScreen test passing. Shouldn't it be the other way around?

**Comment by jfschmakeit** [comment]
Yep, good catch. You implement the `clickOnAndroidHomeIcon` test first and the `clickOnStatistics` next. I have updated the screenshot for the next release.
