### ISSUE TITLE
"Step 7: Espresso Test 2: Adding a note" refers to wrong view

### ISSUE THREAD

**Issue by efung** [googlecodelabs/android-testing#60]
In the following description, after the FAB is clicked, the text says that Espresso will wait for the new screen, by waiting on the View with id `R.id.fab_add_notes`. This should instead reference a view on the new screen, i.e. `R.id.add_note_title`. I've marked the incorrect id in the excerpt below:

> Similar to the previous Espresso test we looked at, we will first find the floating action button (`R.id.fab_add_notes`) and click it:

```
// Click on the add note button
onView(withId(R.id.fab_add_notes)).perform(click());
```

> Next (once the "add note screen" is open) we will enter our note text and save the note. (We don't need to wait for the new screen to open - Espresso will do this automatically for us. It waits until a View with the id **>>>`R.id.fab_add_notes`<<<** can be found.)

```
// Add note title and description
onView(withId(R.id.add_note_title)).perform(typeText(newNoteTitle), closeSoftKeyboard()); // Type new note title
onView(withId(R.id.add_note_description)).perform(typeText(newNoteDescription),
       closeSoftKeyboard()); // Type new note description and close the keyboard
```

**Comment by jfschmakeit** [comment]
Good catch! Yes, the text should refer to "add_note_title" instead, just as it is shown in the code. I have updated the description for the next doc release.
Thanks!
