### ISSUE TITLE
[Bug] Wrong test Activity class in Step 8: Bonus: Espresso-Intents 

### ISSUE THREAD

**Issue by shaobin0604** [googlecodelabs/android-testing#63]
[Android Testing Codelab Step 8: Bonus: Espresso-Intents](https://codelabs.developers.google.com/codelabs/android-testing/index.html#7)

says `androidTestMock/.../AddNoteScreenTest.java`

```
@Rule
public IntentsTestRule<NotesActivity> mNotesIntentsTestRule = new IntentsTestRule<>(NotesActivity.class);
```

actually the Activity class under test should be `AddNoteActivity`

**Comment by jfschmakeit** [comment]
Thanks, fixed in the next doc release. (This was referring to old code that was removed from the codelab. The source code was already correct.)
