### ISSUE TITLE
Step 5, inconsistency with text and screenshot for selecting build variant

### ISSUE THREAD

**Issue by minneapolis-edu** [googlecodelabs/android-testing#65]
Step 5; We are now ready to run the app! section;  text says "choose the prodDebug variant", the screenshot shows prodRelease selected.

![image](https://cloud.githubusercontent.com/assets/10088152/20015415/6086e682-a289-11e6-85b9-d4c8fc147555.png)

Thank you

**Comment by jfschmakeit** [comment]
The screenshot is actually showing that prodDebug is selected, but the highlighting doesn't make that quite obvious. I have updated the screenshot for the next doc release and simply omitted the drop down portion.
