### ISSUE TITLE
Lesson 5 MVP in practice - code doesn't match the lesson.

### ISSUE THREAD

**Issue by sudhirkhanger** [googlecodelabs/android-testing#68]
Hi,

In the lesson 5 MVP in practice, following code is shown to be in `onActivityCreated` but it is actually in .onCreate`.

    mActionsListener = new NotesPresenter(Injection.provideNotesRepository(), this);

**Codelab**
![screenshot_20161120_122122](https://cloud.githubusercontent.com/assets/841656/20461045/e2753ac4-af1b-11e6-9a99-0081f0645e16.png)

**Actual Code**
![screenshot_20161120_121805](https://cloud.githubusercontent.com/assets/841656/20461137/f1549972-af1b-11e6-8168-8049541342c2.png)

Code in concern- https://github.com/googlecodelabs/android-testing/blob/master/app/src/main/java/com/example/android/testing/notes/notes/NotesFragment.java#L79

**Comment by jfschmakeit** [comment]
The source code is actually correct here, the issue is only in the documentation. I have updated the doc to include the correct snippet from onCreate(..) instead. This should be live in the next document release.
