### ISSUE TITLE
[Question] What this code does?

### ISSUE THREAD

**Issue by rhespanhol** [googlecodelabs/android-testing#7]
I'm sorry for opening an issue but i dont know where else i can ask a question:

In the AddNotePresentar constructor there is this line:
addNoteView.setUserActionListener(this); (line 49)

Isn't this redundant because the constructor already set the mActionListener in the AddNoteFragment (line 79) or is there some usecase that i'm not following with that listener?

Cheers

**Comment by slinzner** [comment]
Thanks for reporting this, it's redundant and a bug. I removed it in the next release.
