### ISSUE TITLE
Missing configuration/installation of Code Coverage functionality.

### ISSUE THREAD

**Issue by MPongrac** [googlecodelabs/android-testing#72]
In my installation of Android Studio (2.2.3), there is no Code Coverage selection/configuration.  It would be nice if the codelab could be extended to instruct the user on how to correct such a situation if it exists.

This link will provide the user with basic help on how to configure Code Coverage. 
https://www.jetbrains.com/help/idea/2016.3/code-coverage.html

There are still a few small spelling and grammar mistakes, but we will overlook them. 

This is a very good code lab to help the student get started with writing their own tests.

Kind regards,
MPongrac

**Comment by JoseAlcerreca** [comment]
Revamped the whole codelab with a new code coverage section
