### ISSUE TITLE
Caused by: android.support.test.espresso.IdlingResourceTimeoutException: Wait for [GLOBAL] to become idle timed out

### ISSUE THREAD

**Issue by 1abid** [googlecodelabs/android-testing#74]
I have followed this tutorial series from beginning to the end . I have written this app step by step as I was learning to know how Testing works . every thing was just expected , but some of my instrument tests are showing this error . I have tested those test methods from the "android-testing" repo but those works fine . Can anyone tell What I am doing wrong ???

**Comment by dharmendrainnovify** [comment]
Same issue with me I am getting IdlingResourceTimeoutException: Wait for [GLOBAL] to become idle timed out error after few tests gets done.

**Comment by hussainahmad** [comment]
@1abid  @dharmendrainnovify  Any solution find ? I am getting same Issue

**Comment by JoseAlcerreca** [comment]
Try stackoverflow for these questions.
