### ISSUE TITLE
Step 9 contains incorrect "Espresso-Intents" subheadings

### ISSUE THREAD

**Issue by jakemoritz** [googlecodelabs/android-testing#75]
In Step 9, the "Espresso-Contrib" section, there are two subheadings for the test cases sections labelled "Espresso-Intents Test #". As this is the "Espresso-Contrib" section, the subheadings should be "Espresso-Contrib Test #".

**Comment by dmeng** [comment]
Closing as this section no longer exists as of the latest update. Thanks for catching the mistake though!
