### ISSUE TITLE
Android support v4 and v7

### ISSUE THREAD

**Issue by lambed** [googlecodelabs/android-testing#77]
I never understand how you can publish a codelab that builds just fine however the Espresso test have all types of build errors that are related to support libraries v4 and v7. When will you fix this nonsense and why don't you keep up with this stuff after it's published.

**Comment by mmBs** [comment]
There is no errors, but you need to think about a workaround. In this particular case you need to replace all your dependencies from `compile`, `testCompile` or `androidTestCompile` to `implementation`, `testImplementation` or `androidTestImplementation`. Sth like this:

    dependencies {
      // App's dependencies, including test
      implementation "com.android.support:appcompat-v7:$rootProject.supportLibraryVersion"
      implementation "com.android.support:cardview-v7:$rootProject.supportLibraryVersion"
      implementation "com.android.support:design:$rootProject.supportLibraryVersion"
      implementation "com.android.support:recyclerview-v7:$rootProject.supportLibraryVersion"
      implementation "com.android.support:support-v4:$rootProject.supportLibraryVersion"
      implementation "com.google.guava:guava:$rootProject.guavaVersion"
      implementation "com.github.bumptech.glide:glide:$rootProject.glideVersion"
      implementation "com.android.support.test.espresso:espresso-idling-resource:$rootProject.ext.espressoVersion"

      // Dependencies for local unit tests
      testImplementation "junit:junit:$rootProject.ext.junitVersion"
      testImplementation "org.mockito:mockito-all:$rootProject.ext.mockitoVersion"
      testImplementation "org.hamcrest:hamcrest-all:$rootProject.ext.hamcrestVersion"
      testImplementation "org.powermock:powermock-module-junit4:$rootProject.ext.powerMockito"
      testImplementation "org.powermock:powermock-api-mockito:$rootProject.ext.powerMockito"

      // Android Testing Support Library's runner and rules
      androidTestImplementation "com.android.support.test:runner:$rootProject.ext.runnerVersion"
      androidTestImplementation "com.android.support.test:rules:$rootProject.ext.rulesVersion"

      // Espresso UI Testing dependencies.
      androidTestImplementation "com.android.support.test.espresso:espresso-core:$rootProject.ext.espressoVersion"
      androidTestImplementation "com.android.support.test.espresso:espresso-contrib:$rootProject.ext.espressoVersion"
      androidTestImplementation "com.android.support.test.espresso:espresso-intents:$rootProject.ext.espressoVersion"
    }

I assume you use Android Studio 3.0. Hope that helps.

**Comment by JoseAlcerreca** [comment]
We migrated to androidx already
