### ISSUE TITLE
android.support.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with text: is "Notes cannot be empty"

### ISSUE THREAD

**Issue by mmBs** [googlecodelabs/android-testing#78]
Running `errorShownOnEmptyMessage` test I always get `android.support.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with text: is "Notes cannot be empty"` exception.

These are my dependencies:

```
ext {
  // Sdk and tools
  minSdkVersion = 19
  targetSdkVersion = 26
  compileSdkVersion = 26
  buildToolsVersion = '26.0.1'

  // App dependencies
  supportLibraryVersion = '26.1.0'
  guavaVersion = '20.0'
  glideVersion = '3.6.1'
  junitVersion = '4.12'
  mockitoVersion = '1.10.19'
  powerMockito = '1.6.2'
  hamcrestVersion = '1.3'
  runnerVersion = '1.0.1'
  rulesVersion = '1.0.1'
  espressoVersion = '3.0.1'
}
```

I also replaced deprecated registering / unregistering methods for Idling Resources:

```
@Before public void registerIdlingResource() {
    IdlingRegistry.getInstance()
        .register(mAddNoteIntentsTestRule.getActivity().getCountingIdlingResource());
  }
```

```
@After public void unregisterIdlingResource() {
    IdlingRegistry.getInstance()
        .unregister(mAddNoteIntentsTestRule.getActivity().getCountingIdlingResource());
  }
```

**Comment by lugutori** [comment]
I have the same problem. But according to this: https://github.com/googlecodelabs/android-testing/blob/master/app/src/androidTestMock/java/com/example/android/testing/notes/addnote/AddNoteScreenTest.java (lines 115 - 118) there seems to be a problem with the Snackbar tests

**Comment by dmeng** [comment]
Closing as the corresponding code is no longer used in the codelab as of the latest update. If you're seeing this happen with the new code though, feel free to reopen.

**Comment by bkanchan82** [comment]
I am facing the same problem of  
androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with id: com.getinfino.android:id/contact_number_edt

When running my test. I am using a snackbar conditionally but in my test I am not testing the snackbar scenario.

Please let me know if it requires any other information
