### ISSUE TITLE
Step 10 redundunt links redirection

### ISSUE THREAD

**Issue by IslamSalah** [googlecodelabs/android-testing#82]
In the following paragraph : 

# Idling Resources in Practice
In our app we have wrapped the calls to [Simple](https://github.com/googlecodelabs/android-testing/blob/master/app/src/main/java/com/example/android/testing/notes/util/SimpleCountingIdlingResource.java) [CountingIdlingResource](https://github.com/googlecodelabs/android-testing/blob/master/app/src/main/java/com/example/android/testing/notes/util/SimpleCountingIdlingResource.java)...

**I believe that we should have only one link redirection by concatenating the 2 words to be :** 

In our app we have wrapped the calls to [SimpleCountingIdlingResource](https://github.com/googlecodelabs/android-testing/blob/master/app/src/main/java/com/example/android/testing/notes/util/SimpleCountingIdlingResource.java)...

**Comment by dmeng** [comment]
Closing as the associated paragraph was removed in the latest update.

There _shouldn't_ be another instance of this kind of redundant link in the codelab now, but feel free to reopen and edit if we missed a spot.
