### ISSUE TITLE
NotesPresenter is not tested to verify that it sets the progress indicator on the view to true after it starts loading notes

### ISSUE THREAD

**Issue by idow09** [googlecodelabs/android-testing#88]
When NotesPresenter#loadNotes is invoked the NotesPresenter should call `setProgressIndicator(true)` on the view and indeed it does. However, this behaviour is not tested and therefore the tests still pass if I remove the line `mNotesView.setProgressIndicator(true);`. I tried it of course and it's true...
The test should include a verification: `verify(mNotesView).setProgressIndicator(true);` after `mNotesPresenter.loadNotes(true);`

**Comment by dmeng** [comment]
Closing as the associated code is no longer there as of the latest update.

If there's another spot like this we've missed though, feel free to let us know.
