### ISSUE TITLE
Rename NotesDetailPresenterTest to NoteDetailPresenterTest

### ISSUE THREAD

**Issue by idow09** [googlecodelabs/android-testing#89]
Stick to convention and rename `NotesDetailPresenterTest` to `NoteDetailPresenterTest`.
Currently the test class does not corespond to its production class (for example pressing Ctrl+Shift+T won't take you there).

**Comment by dmeng** [comment]
Closing as we removed those two files in the latest update.

Not going to lie though, I did look at the spelling of what we have now just to make absolute sure we didn't repeat the same typo.
