### ISSUE TITLE
Error while compiling the project

### ISSUE THREAD

**Issue by SanjayMallur** [googlecodelabs/android-testing#90]
Error:org/jetbrains/plugins/gradle/model/ProjectImportActionorg/jetbrains/plugins/gradle/model/ProjectImportAction

**Comment by dmeng** [comment]
@SanjayMallur If you're still getting this, we need more than just the one line. What IDE are you using (and what version?) What version of the gradle plugin are you using? What part of the compilation failed?

**Comment by SanjayMallur** [comment]
@dmeng sorry it's too old issue, recently I did not check it. We can close this for now.
