### ISSUE TITLE
Animations Off Cause addNoteToNotesList in Step 7 to Fail

### ISSUE THREAD

**Issue by scophotog** [googlecodelabs/android-testing#92]
I turned off the animations as suggested in Step 7 Writing UI Tests With Espresso

https://codelabs.developers.google.com/codelabs/android-testing/index.html?index=..%2F..%2Findex#6

- Window animation scale
- Transition animation scale
- Animator duration scale

The test fails if I turn all of these off.
If I leave Animator duration scale on, there seems to be enough delay from the animation and the test will pass. The Window and Transition animation scale seems to have no affect on the test.

I was performing this in a Nexus 5x emulator running 7.1.1

**Comment by Yubyf** [comment]
It seems that I must add delay time before `scrollTo`: `Thread.sleep(200)` and then the test will pass.

**Comment by scophotog** [comment]
I found the same to be true. Step 10 talks about the EspressoIdlingResource.increment() and .decrement() to signal to espresso when the app is busy. I tried moving the decrement to after the setProgressIndicator(false) and I ended up with the same result.

**Comment by Kiruel** [comment]
The same problem for me, I just ON Animator to 1sec. And it's work.
