### ISSUE TITLE
Step 8 has double code

### ISSUE THREAD

**Issue by tresvitae** [googlecodelabs/android-testing#96]
Method selectTakeImageFromMenu() shown at first time should be deleted because on the next line it's explaining:

Next we verify that no thumbnail image is being shown as a sanity check - no image has been taken yet.

// Check thumbnail view is not displayed
        onView(withId(R.id.add_note_image_thumbnail)).check(matches(not(isDisplayed())));

**selectTakeImageFromMenu();**

We select the "Add image" option in the menu using a short helper method:

selectTakeImageFromMenu();

**Comment by tresvitae** [comment]
Also not() is colored on red so that make little confuse.

**Comment by dmeng** [comment]
Closing as the associated section is gone as of the latest update.

There _shouldn't_ be another instance of this happening, but feel free to reopen if we missed a spot.
