### ISSUE TITLE
MVVM + Repositories - is the recommended architecture

### ISSUE THREAD

**Issue by OrenBochman** [googlecodelabs/android-testing#97]
Please update/expand this lab to show how to test a MVVM app and the more common newly introduced jetpack components - LiveData, Room, Repositories, LifecycleObserver.

In particular I'd like to see how MVVM allows testing more code in the non-instrumented branch!

**Comment by dmeng** [comment]
Latest update switches to MVVM and touches on some of the components that you asked for. Hope you like it!
