### ISSUE TITLE
Step 1-5: Could not find lint-gradle-api.jar

### ISSUE THREAD

**Issue by serializer** [googlecodelabs/android-testing#98]
On building Step 1-5 project, I am getting an error about a resource not available anymore.

Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.1.2).
Searched in the following locations:
    **https://jcenter.bintray.com/com/android/tools/lint/lint-gradle-api/26.1.2/lint-gradle-api-26.1.2.jar**

**Comment by nyabongo** [comment]
If any one else has this problem, editing  build.gradle as below should help
```
buildscript {
    repositories {
        maven { url 'https://dl.google.com/dl/android/maven2' }
        jcenter()
        google()
    }
 ...

allprojects {
    repositories {
        maven { url 'http://repo1.maven.org/maven2' }
        jcenter()
        google()
    }
}
...

**Comment by pspencil** [comment]
Alternatively, just try to move "google()" above "jcenter()"

**Comment by serializer** [comment]
> Alternatively, just try to move "google()" above "jcenter()"

that worked perfectly!! but how??

**Comment by pspencil** [comment]
> > Alternatively, just try to move "google()" above "jcenter()"
> 
> that worked perfectly!! but how??

Oh. That's because the bundle exists in google() (and no longer in jcenter) and order matters for gradle configs.
